data:
  csv_path: "data/winequality-red.csv"
  target: "quality"
  test_size: 0.2
  val_size: 0.1
  random_state: 42

model:
  type: "random_forest"    # options: "linear", "random_forest"
  params:
    n_estimators: 300
    max_depth: 12
    random_state: 42

preprocess:
  scale_numeric: true

tracking:
  use_mlflow: true
  experiment_name: "wine-quality"
  artifacts_dir: "artifacts"
